### PR TITLE
Tooling: TestCafe + Travis & SauceLab Automation

### PR DESCRIPTION
**Pull request by mis046**
- Added TestCafe to our pipeline.
- Edited core-hello demo html file for testing
- Wrote an example ui test
- All tests will be run by TravisCi with SauceLab when pushing
- UI tests would be placed under test_ui/
Documentation here:
https://docs.google.com/document/d/1JgafhXXTFVwgZRzyta6yDG143iUOu91fiwi2MtrqSaM/edit

### CODE REVIEW

**Comment by ShaneNielsen1234** [comment]
Make ticket to fix safari bug

**Comment by fmavb** [comment]
Does anyone know a quick solution to merge 16000 lines of code in package_lock.json?

**Comment by mis046** [comment]
> Does anyone know a quick solution to merge 16000 lines of code in package_lock.json?

I did it last time by eye since I know I only added sauce lab. But I don't know what to do not. Maybe delete one of them?

**Comment by mis046** [comment]
> Does anyone know a quick solution to merge 16000 lines of code in package_lock.json?

Nate: "best way is to delete it"

**Comment by Chris-Synnott** [comment]
Looks good to me!

**Pull request merged**
